name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: |
          echo $POSTMAN_API_KEY
          echo "noman razvi"
          postman login --with-api-key $POSTMAN_API_KEY
      - name: Run API tests
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          postman collection run "${GITHUB_WORKSPACE}/postman/collections/New Collection.json" --integration-id "122718-${GITHUB_RUN_ID}"
          postman collection run "${GITHUB_WORKSPACE}/postman/collections/New Collection(1).json" --integration-id "122718-${GITHUB_RUN_ID}"
